#!/usr/bin/env python3
"""Cuts a new release.

Bumps the version in MODULE.bazel, commits that change on a new
"release-vX.Y.Z" branch, pushes the branch to the "github" remote, and opens
a pull request for it.

Once the pull request is merged, the "Tag release" GitHub Actions workflow
(.github/workflows/release.yml) tags the merge commit and publishes a GitHub
release with an autogenerated source archive.
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

repo_root = Path(__file__).resolve().parent.parent
module_bazel_file_name = repo_root / "MODULE.bazel"
MAIN_BRANCH = "main"
VERSION_RE = re.compile(r'(?m)^(\s*version\s*=\s*)"([^"]+)"')


def git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=repo_root, check=True, capture_output=True, text=True
    )
    return result.stdout.strip()


def parse_version(version: str) -> tuple[int, ...]:
    if not re.fullmatch(r"\d+(\.\d+)*", version):
        sys.exit(f"error: version {version!r} must look like 1.2.3")
    return tuple(int(part) for part in version.split("."))


def current_version() -> str:
    match = VERSION_RE.search(module_bazel_file_name.read_text())
    if not match:
        sys.exit(f"error: could not find a version in {module_bazel_file_name}")
    return match.group(2)


def update_version(new_version: str) -> None:
    text = module_bazel_file_name.read_text()
    new_text, count = VERSION_RE.subn(rf'\1"{new_version}"', text, count=1)
    if count != 1:
        sys.exit(f"error: could not update version in {module_bazel_file_name}")
    module_bazel_file_name.write_text(new_text)


def check_on_main() -> None:
    branch = git("rev-parse", "--abbrev-ref", "HEAD")
    if branch != MAIN_BRANCH:
        sys.exit(f"error: must be on branch {MAIN_BRANCH!r}, currently on {branch!r}")


def check_clean_working_tree() -> None:
    # Untracked files are fine; only complain about staged changes or
    # modifications to already-checked-in files.
    status = git("status", "--porcelain")
    problems = [line for line in status.splitlines() if not line.startswith("??")]
    if problems:
        sys.exit("error: working tree has uncommitted changes:\n" + "\n".join(problems))


def check_up_to_date_with_remote(remote: str) -> None:
    git("fetch", remote, MAIN_BRANCH)
    local = git("rev-parse", "HEAD")
    remote_head = git("rev-parse", f"{remote}/{MAIN_BRANCH}")
    if local != remote_head:
        sys.exit(
            f"error: local {MAIN_BRANCH} ({local[:8]}) differs from "
            f"{remote}/{MAIN_BRANCH} ({remote_head[:8]}); pull or push first"
        )


def check_remote_exists(remote: str) -> None:
    remotes = git("remote").splitlines()
    if remote not in remotes:
        sys.exit(f"error: no git remote named {remote!r} (found: {', '.join(remotes)})")


def branch_exists(branch: str) -> bool:
    return bool(git("branch", "--list", branch))


def create_pull_request(branch: str, new_version: str, remote: str) -> None:
    if shutil.which("gh") is None:
        print("note: 'gh' CLI not found; skipping pull request creation.")
        print(f"Push succeeded. Open a pull request for {branch!r} manually.")
        return
    subprocess.run(
        ["gh", "pr", "create"]
        + ["--base", MAIN_BRANCH]
        + ["--head", branch]
        + ["--title", f"Release v{new_version}"]
        + ["--body", f"Bump version to {new_version}."],
        cwd=repo_root,
        check=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="new version number, e.g. 1.2.3")
    parser.add_argument(
        "--remote",
        default="github",
        help="git remote to push to (default: %(default)s)",
    )
    parser.add_argument(
        "--no-pr",
        action="store_true",
        help="push the branch but skip creating a pull request",
    )
    args = parser.parse_args()

    new_version = args.version
    new_tuple = parse_version(new_version)

    check_remote_exists(args.remote)
    check_on_main()
    check_clean_working_tree()
    check_up_to_date_with_remote(args.remote)

    old_version = current_version()
    if new_tuple <= parse_version(old_version):
        sys.exit(
            f"error: new version {new_version} is not newer than current version {old_version}"
        )

    branch = f"release-v{new_version}"
    if branch_exists(branch):
        sys.exit(f"error: local branch {branch!r} already exists")

    print(f"Bumping version {old_version} -> {new_version} on branch {branch!r}")
    git("checkout", "-b", branch)
    try:
        update_version(new_version)
        git("add", str(module_bazel_file_name.relative_to(repo_root)))
        git("commit", "-m", f"Release v{new_version}")
        git("push", "--set-upstream", args.remote, branch)
    except subprocess.CalledProcessError as error:
        print(error.stdout, error.stderr, file=sys.stderr)
        git("checkout", MAIN_BRANCH)
        git("branch", "-D", branch)
        sys.exit("error: release preparation failed; rolled back local branch")

    print(f"Pushed branch {branch!r} to remote {args.remote!r}.")

    if args.no_pr:
        return
    create_pull_request(branch, new_version, args.remote)


if __name__ == "__main__":
    main()
