name: Pre-commit checks
on:
  push:
    branches: [main, develop, test-github-actions]
  pull_request:
    branches: [main, develop, test-github-actions]
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
